//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLabelerStation.ZDT {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZDT.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendDataToSer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string sendDataToSer(string username, string password, string equid, string parameterName, string parameterValue, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDataToSerGrp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string updateDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterValue, string parameterCondi, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteDataToSerGrp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string deleteDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterValue, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataFromSer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getDataFromSer(string username, string password, string equid, string groupid, string funid, string pValue, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataByPartnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getDataByPartnum(string partnum, string begindate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendDataToSerGrp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string sendDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterName, string parameterValue, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendDataToSerGrp2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string sendDataToSerGrp2(string username, string password, string equid, string groupid, string parameterName, string parameterValue, string createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnSPIBarmark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string ReturnSPIBarmark(string Barcode, string Side);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : GeneralLabelerStation.ZDT.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<GeneralLabelerStation.ZDT.Service1Soap>, GeneralLabelerStation.ZDT.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendDataToSer(string username, string password, string equid, string parameterName, string parameterValue, string createDate) {
            return base.Channel.sendDataToSer(username, password, equid, parameterName, parameterValue, createDate);
        }
        
        public string updateDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterValue, string parameterCondi, string createDate) {
            return base.Channel.updateDataToSerGrp(username, password, equid, groupid, funid, parameterValue, parameterCondi, createDate);
        }
        
        public string deleteDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterValue, string createDate) {
            return base.Channel.deleteDataToSerGrp(username, password, equid, groupid, funid, parameterValue, createDate);
        }
        
        public System.Data.DataSet getDataFromSer(string username, string password, string equid, string groupid, string funid, string pValue, string createDate) {
            return base.Channel.getDataFromSer(username, password, equid, groupid, funid, pValue, createDate);
        }
        
        public System.Data.DataSet getDataByPartnum(string partnum, string begindate) {
            return base.Channel.getDataByPartnum(partnum, begindate);
        }
        
        public string sendDataToSerGrp(string username, string password, string equid, string groupid, string funid, string parameterName, string parameterValue, string createDate) {
            return base.Channel.sendDataToSerGrp(username, password, equid, groupid, funid, parameterName, parameterValue, createDate);
        }
        
        public string sendDataToSerGrp2(string username, string password, string equid, string groupid, string parameterName, string parameterValue, string createDate) {
            return base.Channel.sendDataToSerGrp2(username, password, equid, groupid, parameterName, parameterValue, createDate);
        }
        
        public string ReturnSPIBarmark(string Barcode, string Side) {
            return base.Channel.ReturnSPIBarmark(Barcode, Side);
        }
    }
}
